apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: amoneyplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amoneyplan-backend:latest
        imagePullPolicy: Never # Use locally built image
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "amoneyplan.settings"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        command: ["/bin/bash", "-c"]
        args:
          - |
            python manage.py migrate &&
            python manage.py init_db --sample &&
            python manage.py runserver 0.0.0.0:8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: amoneyplan
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort