kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8000
    protocol: TCP
  - containerPort: 30432
    hostPort: 5432
    protocol: TCP
  extraMounts:
  - hostPath: ../backend/src
    containerPath: /src
