# Generated by Django 5.1.7 on 2025-03-30 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmembership",
            name="invited_by_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who sent the invitation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
