# Generated by Django 5.1.7 on 2025-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
