# Generated by Django 5.1.7 on 2025-05-20 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import amoneyplan.common.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accountmembership_invited_by_user"),
        ("money_plans", "0002_account_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanShareLink",
            fields=[
                (
                    "id",
                    amoneyplan.common.models.SafeCuid16Field(
                        default=amoneyplan.common.models.generate_safe_cuid16,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="money_plans.moneyplan",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
